# Generated by Django 2.2.1 on 2019-06-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180708_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('hora', models.TextField(blank=True, null=True)),
                ('encargado', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
