# Generated by Django 2.2.1 on 2019-06-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190612_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='encargado',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='hora',
            field=models.CharField(max_length=120),
        ),
    ]
