# Generated by Django 2.2.1 on 2019-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tema', models.CharField(max_length=120)),
            ],
        ),
    ]
